[package]
name = "mr_autoauto"
version = "0.1.0"
edition = "2021"

[features]
default = []
gaussian_splats = ["dep:bevy_gaussian_splatting"]

[dependencies]
bevy = { version = "0.17", default-features = true }
bevy_gaussian_splatting = { version = "6.0", optional = true }

[patch.crates-io]
bevy_gaussian_splatting = { path = "vendor/bevy_gaussian_splatting" }
