[[sprites]]
id = "vehicle_starter_car_sprite"
path = "sprites/vehicle_starter_car.png"

[[sprites]]
id = "enemy_grunt_sprite"
path = "sprites/enemy_grunt.png"

[[sprites]]
id = "turret_base_sprite"
path = "sprites/turret_base.png"

[[models]]
id = "vehicle_starter_car"
scene_path = "models/vehicles/car_rally.glb#Scene0"
root_node = "geometry_0.root.0"
wheel_nodes = [
  "geometry_0.004.root.3",
  "geometry_0.006.root.5",
  "geometry_0.005.root.4",
  "geometry_0.003.root.2",
]
turret_node = "geometry_0.002.root.1"

[[models]]
id = "enemy_grunt_model"
scene_path = "models/enemies/grunt.glb#Scene0"
root_node = "GruntRoot"
wheel_nodes = ["WheelDummy"]

[[models]]
id = "enemy_roadside_turret"
scene_path = "models/enemies/owl_tower.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_high_bomber"
scene_path = "models/enemies/owl_bomber.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_grunt_walker"
scene_path = "models/enemies/beetle_rough.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_charger_buggy"
scene_path = "models/enemies/beetle_green.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_drone_flier"
scene_path = "models/enemies/bullfinch.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[splats]]
id = "museum_hall_01"
path = "splats/museum_hall_01.gcloud"

[[splats]]
id = "garage_alley_01"
path = "splats/garage_alley_01.gcloud"

[[splats]]
id = "mystical"
path = "splats/mystical.ply"

[[audio]]
id = "sfx_player_shot"
path = "audio/sfx/player_shot.ogg"

[[audio]]
id = "sfx_enemy_shot"
path = "audio/sfx/enemy_shot.ogg"

[[audio]]
id = "sfx_hit"
path = "audio/sfx/hit.ogg"
