[[sprites]]
id = "vehicle_starter_car_sprite"
path = "sprites/autoauto_logo.jpg"

[[sprites]]
id = "enemy_grunt_sprite"
path = "sprites/autoauto_logo.jpg"

[[sprites]]
id = "turret_base_sprite"
path = "sprites/autoauto_logo.jpg"

[[models]]
id = "vehicle_starter_car"
scene_path = "models/vehicles/car_rally.glb#Scene0"
root_node = "geometry_0.root.0"
wheel_nodes = [
  "geometry_0.004.root.3",
  "geometry_0.006.root.5",
  "geometry_0.005.root.4",
  "geometry_0.003.root.2",
]
turret_node = "geometry_0.002.root.1"

[[models]]
id = "enemy_grunt_model"
scene_path = "models/enemies/beetle_rough.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_roadside_turret"
scene_path = "models/enemies/owl_tower.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_high_bomber"
scene_path = "models/enemies/owl_bomber.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_grunt_walker"
scene_path = "models/enemies/beetle_rough.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_charger_buggy"
scene_path = "models/enemies/beetle_green.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_drone_flier"
scene_path = "models/enemies/bullfinch.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[models]]
id = "enemy_segment_boss_drone"
scene_path = "models/enemies/bullfinch.glb#Scene0"
root_node = "ROOT"
wheel_nodes = ["ROOT"]

[[splats]]
id = "museum_hall_01"
path = "splats/museum_hall_01.gcloud"

[[splats]]
id = "garage_alley_01"
path = "splats/garage_alley_01.gcloud"

[[splats]]
id = "mystical"
path = "splats/mystical.ply"

[[splats]]
id = "castle"
path = "splats/castle.ply"

[[splats]]
id = "cemetery"
path = "splats/cemetery.ply"

[[audio]]
id = "sfx_player_shot"
path = "audio/sfx/gun_shot.wav"

[[audio]]
id = "sfx_enemy_shot"
path = "audio/sfx/missile_launch.wav"

[[audio]]
id = "sfx_hit"
path = "audio/sfx/gun_hit.wav"

[[audio]]
id = "sfx_engine_loop"
path = "audio/sfx/engine.wav"

[[audio]]
id = "sfx_explode"
path = "audio/sfx/explode.wav"

[[audio]]
id = "sfx_gun_hit"
path = "audio/sfx/gun_hit.wav"

[[audio]]
id = "sfx_gun_miss"
path = "audio/sfx/gun_miss.wav"

[[audio]]
id = "sfx_gun_shot"
path = "audio/sfx/gun_shot.wav"

[[audio]]
id = "sfx_missile_hit"
path = "audio/sfx/missile_hit.wav"

[[audio]]
id = "sfx_missile_launch"
path = "audio/sfx/missile_launch.wav"

[[audio]]
id = "music_background_loop"
path = "audio/music.wav"
