[[backgrounds]]
color = [
    0.16,
    0.19,
    0.24,
]
id = "museum_hall_01"
loop_length_m = 0.0
offset_x_m = 250.0
offset_y_m = -30.0
offset_z_m = 150.0
parallax = 0.5
placeholder = "box"
scale_x = 6.5
scale_y = -9.0
scale_z = -11.0
splat_asset_id = "mystical"

[[backgrounds]]
color = [
    0.12,
    0.14,
    0.16,
]
id = "garage_alley_01"
loop_length_m = 0.0
offset_x_m = 0.0
offset_y_m = 0.0
offset_z_m = 0.0
parallax = 0.45
placeholder = "polygon"
scale_x = 1.0
scale_y = 1.0
scale_z = 1.0
