[app]
debug_overlay = true
default_vehicle = "starter_car"
fixed_timestep_hz = 60.0
starting_environment = "normal"

[sfx]
enabled = true
master_volume = 1.0
music_volume = 0.42
pitch_random_min = 0.94
pitch_random_max = 1.06
engine_volume = 0.32
engine_base_speed = 0.82
engine_accel_speed_boost = 0.56
engine_velocity_speed_boost = 0.34
engine_idle_gain = 0.30
engine_load_gain = 0.68
engine_pitch_jitter = 0.015
gun_shot_volume = 0.30
gun_hit_volume = 0.26
gun_miss_volume = 0.18
missile_launch_volume = 0.34
missile_hit_volume = 0.32
explode_volume = 0.40

[pickups]
bounce_damping = 0.28
coin_jitter_x_m = 0.24
coin_jitter_y_m = 0.18
coin_pickup_radius_m = 0.44
coin_radius_m = 0.32
coin_score_min = 8
coin_score_scale = 0.55
coin_spin_speed_max_rad_s = 5.2
coin_spin_speed_min_rad_s = 2.8
collection_radius_m = 1.45
despawn_behind_player_m = 96.0
despawn_seconds = 18.0
drop_horizontal_spread_mps = 4.2
drop_vertical_speed_max_mps = 5.8
drop_vertical_speed_min_mps = 3.2
gravity_mps2 = 22.0
ground_slide_damping = 0.94
ground_stop_speed_mps = 0.85
health_box_size_m = 0.62
health_drop_chance = 0.24
health_drop_heal_amount = 22.0
health_jitter_x_m = 0.28
health_jitter_y_m = 0.14
health_pickup_radius_m = 0.5
health_spin_speed_max_rad_s = 3.2
health_spin_speed_min_rad_s = -3.2

[run_upgrades]
choices_per_offer = 2
coins_per_offer = 5

[[run_upgrades.options]]
effect = "health_flat"
id = "health_plus_10"
label = "Health +10"
max_stacks = 50
value = 10.0

[[run_upgrades.options]]
effect = "weapon_fire_rate_percent"
id = "gun_fire_rate_plus_10_percent"
label = "Gun Fire Rate +10%"
max_stacks = 50
value = 0.1

[[run_upgrades.options]]
effect = "missile_fire_rate_percent"
id = "missile_fire_rate_plus_10_percent"
label = "Missile Fire Rate +10%"
max_stacks = 50
value = 0.1

[[run_upgrades.options]]
effect = "vehicle_power_percent"
id = "vehicle_power_plus_10_percent"
label = "Car Power +10%"
max_stacks = 50
value = 0.1

[[run_upgrades.options]]
effect = "turret_cone_degrees_flat"
id = "turret_cone_plus_5_degrees"
label = "Targeting Cone +5 deg"
max_stacks = 30
value = 5.0

[[run_upgrades.options]]
effect = "missile_turn_rate_percent"
id = "missile_turn_rate_plus_10_percent"
label = "Missile Turn Speed +10%"
max_stacks = 50
value = 0.1

[[run_upgrades.options]]
effect = "turret_range_percent"
id = "turret_range_plus_10_percent"
label = "Targeting Range +10%"
max_stacks = 50
value = 0.1

[scoring]
airtime_points_per_second = 14.0
flip_points = 120
no_damage_bonus = 600
points_per_meter = 1.0
wheelie_points_per_second = 18.0

[terrain]
base_height = -8.5
ground_lowering_m = 3.0
ramp_slope = 0.0
wave_a_amplitude = 2.1
wave_a_frequency = 0.18
wave_b_amplitude = 0.9
wave_b_frequency = 0.558
wave_c_amplitude = 3.4
wave_c_frequency = 0.045
