[[segment_sequence]]
id = "castle"
length = 120.0
environment = "normal"
spawn_set = "starter_wave"

[[segment_sequence]]
id = "mythical"
length = 100.0
environment = "normal"
spawn_set = "starter_wave"
