[[vehicles]]
acceleration = 160.0
air_base_damping = 0.05000000074505806
air_env_drag_factor = 0.44999998807907104
air_max_rotation_speed = 2.0
air_pitch_torque = 130.0
brake_strength = 126.0
camera_look_ahead_factor = 1.7999999523162842
camera_look_ahead_max = 20.0
camera_look_ahead_min = -10.5
default_weapon_id = "player_auto"
front_drive_ratio = 0.30000001192092896
gravity_scale = 1.7000000476837158
ground_coast_damping = 0.14000000059604645
health = 100.0
id = "starter_car"
linear_inertia = 8.0
linear_speed_scale = 1.0
max_fall_speed = 18.0
max_forward_speed = 16.5
max_reverse_speed = 9.0
missile_fire_interval_seconds = 2.0
rear_drive_traction_assist_distance_m = 0.20000000298023224
rear_drive_traction_assist_min_factor = 0.7200000286102295
rotational_inertia = 2.0
secondary_weapon_id = "player_missile"
suspension_damping = 160.0
suspension_max_compression_m = 0.46000000834465027
suspension_max_extension_m = 0.46000000834465027
suspension_rest_length_m = 0.7799999713897705
suspension_stiffness = 570.0
tire_longitudinal_grip = 1.0
tire_slip_grip_floor = 0.6200000047683716
turret_cone_degrees = 60.0
turret_range_m = 30.0
turret_target_priority = "nearest"
