[[weapons]]
id = "player_auto"
projectile_type = "bullet"
bullet_speed = 42.0
fire_rate = 5.0
spread_degrees = 2.0
damage = 7.0
burst_count = 1
burst_interval_seconds = 0.0
muzzle_offset_x = 2.0
muzzle_offset_y = 0.1
projectile_drag = 0.03
projectile_lifetime_seconds = 2.8
missile_gravity_scale = 1.0
homing_turn_rate_degrees = 0.0

[[weapons]]
id = "enemy_pea_shooter"
projectile_type = "bullet"
bullet_speed = 24.0
fire_rate = 1.2
spread_degrees = 0.0
damage = 4.0
burst_count = 1
burst_interval_seconds = 0.0
muzzle_offset_x = 1.2
muzzle_offset_y = 0.0
projectile_drag = 0.02
projectile_lifetime_seconds = 2.2
missile_gravity_scale = 1.0
homing_turn_rate_degrees = 0.0
