[[weapons]]
id = "player_auto"
projectile_type = "bullet"
bullet_speed = 42.0
fire_rate = 5.0
spread_degrees = 2.0
damage = 7.0
burst_count = 1
burst_interval_seconds = 0.0
muzzle_offset_x = 2.0
muzzle_offset_y = 0.1
projectile_drag = 0.03
projectile_lifetime_seconds = 2.8
missile_gravity_scale = 1.0
homing_turn_rate_degrees = 0.0

[[weapons]]
id = "enemy_pea_shooter"
projectile_type = "bullet"
bullet_speed = 24.0
fire_rate = 1.2
spread_degrees = 0.0
damage = 4.0
burst_count = 1
burst_interval_seconds = 0.0
muzzle_offset_x = 1.2
muzzle_offset_y = 0.0
projectile_drag = 0.02
projectile_lifetime_seconds = 2.2
missile_gravity_scale = 1.0
homing_turn_rate_degrees = 0.0

[[weapons]]
id = "player_missile"
projectile_type = "missile"
bullet_speed = 21.0
fire_rate = 0.5
spread_degrees = 0.0
damage = 16.0
burst_count = 1
burst_interval_seconds = 0.0
muzzle_offset_x = 2.1
muzzle_offset_y = 0.25
projectile_drag = 0.08
projectile_lifetime_seconds = 4.2
missile_gravity_scale = 0.18
homing_turn_rate_degrees = 95.0
